-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 17:57:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(70) NULL,
  `login` VARCHAR(30) NULL,
  `password` VARCHAR(10) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `mydb`.`gouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gouts` (
  `idgouts` INT NOT NULL AUTO_INCREMENT,
  `libellegouts` VARCHAR(50) NULL,
  PRIMARY KEY (`idgouts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensgouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensgouts` (
  `idtsensgouts` INT NOT NULL AUTO_INCREMENT,
  `libellesensgouts` VARCHAR(45) NULL,
  PRIMARY KEY (`idtsensgouts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gouts_has_sensgouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gouts_has_sensgouts` (
  `gouts_idgouts` INT NOT NULL,
  `sensgouts_idtsensgouts` INT NOT NULL,
  PRIMARY KEY (`gouts_idgouts`, `sensgouts_idtsensgouts`),
  INDEX `fk_gouts_has_sensgouts_sensgouts1_idx` (`sensgouts_idtsensgouts` ASC) VISIBLE,
  INDEX `fk_gouts_has_sensgouts_gouts1_idx` (`gouts_idgouts` ASC) VISIBLE,
  CONSTRAINT `fk_gouts_has_sensgouts_gouts1`
    FOREIGN KEY (`gouts_idgouts`)
    REFERENCES `mydb`.`gouts` (`idgouts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gouts_has_sensgouts_sensgouts1`
    FOREIGN KEY (`sensgouts_idtsensgouts`)
    REFERENCES `mydb`.`sensgouts` (`idtsensgouts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartographie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartographie` (
  `idcartographie` INT NOT NULL AUTO_INCREMENT,
  `libellecartographie` VARCHAR(100) NULL,
  `latitudecartographie` DECIMAL NULL,
  `longitudecartographie` DECIMAL NULL,
  PRIMARY KEY (`idcartographie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experience` (
  `idcartographie` INT NULL,
  `iduser` VARCHAR(45) NULL,
  `idgouts` VARCHAR(45) NULL,
  `intensite` VARCHAR(45) NULL,
  `idexp` INT NOT NULL AUTO_INCREMENT,
  `maj` DATE NULL,
  INDEX `fk_cartographie_has_gouts_cartographie1_idx` (`idcartographie` ASC) VISIBLE,
  PRIMARY KEY (`idexp`),
  CONSTRAINT `fk_cartographie_has_gouts_cartographie1`
    FOREIGN KEY (`idcartographie`)
    REFERENCES `mydb`.`cartographie` (`idcartographie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur_has_gouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur_has_gouts` (
  `utilisateur_iduser` INT NOT NULL,
  `gouts_idgouts` INT NOT NULL,
  `cartographie_idcartographie` INT NOT NULL,
  PRIMARY KEY (`utilisateur_iduser`, `gouts_idgouts`, `cartographie_idcartographie`),
  INDEX `fk_utilisateur_has_gouts_gouts1_idx` (`gouts_idgouts` ASC) VISIBLE,
  INDEX `fk_utilisateur_has_gouts_utilisateur1_idx` (`utilisateur_iduser` ASC) VISIBLE,
  INDEX `fk_utilisateur_has_gouts_cartographie1_idx` (`cartographie_idcartographie` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_has_gouts_utilisateur1`
    FOREIGN KEY (`utilisateur_iduser`)
    REFERENCES `mydb`.`utilisateur` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_gouts_gouts1`
    FOREIGN KEY (`gouts_idgouts`)
    REFERENCES `mydb`.`gouts` (`idgouts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_gouts_cartographie1`
    FOREIGN KEY (`cartographie_idcartographie`)
    REFERENCES `mydb`.`cartographie` (`idcartographie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
