-- MySQL Script generated by MySQL Workbench
-- Thu Jan 31 23:50:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `idingredient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`refrigerateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`refrigerateur` (
  `idrefrigerateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idrefrigerateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utiliser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utiliser` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `refrigerateur_idrefrigerateur` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `refrigerateur_idrefrigerateur`),
  INDEX `fk_utilisateur_has_refrigerateur_refrigerateur1_idx` (`refrigerateur_idrefrigerateur` ASC) VISIBLE,
  INDEX `fk_utilisateur_has_refrigerateur_utilisateur_idx` (`utilisateur_idutilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_has_refrigerateur_utilisateur`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_refrigerateur_refrigerateur1`
    FOREIGN KEY (`refrigerateur_idrefrigerateur`)
    REFERENCES `mydb`.`refrigerateur` (`idrefrigerateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recettes` (
  `idrecettes` INT NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(45) NULL,
  `niveau` VARCHAR(45) NULL,
  `tempsPreparation` VARCHAR(45) NULL,
  `nbpersonnes` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecettes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recettes_has_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recettes_has_ingredient` (
  `recettes_idrecettes` INT NOT NULL,
  `ingredient_idingredient` INT NOT NULL,
  PRIMARY KEY (`recettes_idrecettes`, `ingredient_idingredient`),
  INDEX `fk_recettes_has_ingredient_ingredient1_idx` (`ingredient_idingredient` ASC) VISIBLE,
  INDEX `fk_recettes_has_ingredient_recettes1_idx` (`recettes_idrecettes` ASC) VISIBLE,
  CONSTRAINT `fk_recettes_has_ingredient_recettes1`
    FOREIGN KEY (`recettes_idrecettes`)
    REFERENCES `mydb`.`recettes` (`idrecettes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recettes_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_idingredient`)
    REFERENCES `mydb`.`ingredient` (`idingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idproduit` INT NOT NULL,
  `nomProduit` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contenir` (
  `produit_idproduit` INT NOT NULL,
  `ingredient_idingredient` INT NOT NULL,
  PRIMARY KEY (`produit_idproduit`, `ingredient_idingredient`),
  INDEX `fk_produit_has_ingredient_ingredient1_idx` (`ingredient_idingredient` ASC) VISIBLE,
  INDEX `fk_produit_has_ingredient_produit1_idx` (`produit_idproduit` ASC) VISIBLE,
  CONSTRAINT `fk_produit_has_ingredient_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `mydb`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_idingredient`)
    REFERENCES `mydb`.`ingredient` (`idingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
