-- MySQL Script generated by MySQL Workbench
-- Fri Jan 25 16:55:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flux_ontostats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flux_ontostats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ruchemiel` DEFAULT CHARACTER SET latin1 ;
USE `ruchemiel` ;

-- -----------------------------------------------------
-- Table `flux_ontostats`.`abeille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`abeille` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`abeille` (
  `id_abeille` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `ruche_id_ruche` INT NOT NULL,
  PRIMARY KEY (`id_abeille`, `ruche_id_ruche`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`abeille_has_geo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`abeille_has_geo` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`abeille_has_geo` (
  `abeille_id_abeille` INT NOT NULL,
  `geo_id_geo` INT NOT NULL,
  `temps` DATETIME NULL,
  PRIMARY KEY (`abeille_id_abeille`, `geo_id_geo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_acti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_acti` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_acti` (
  `acti_id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `desc` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`acti_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_doc` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_doc` (
  `doc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `titre` VARCHAR(5000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lft` INT(11) NOT NULL,
  `rgt` INT(11) NOT NULL,
  `tronc` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `poids` INT(11) NOT NULL DEFAULT '1',
  `maj` DATETIME NOT NULL,
  `pubDate` DATETIME NOT NULL,
  `note` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `total_posts` INT(11) NOT NULL,
  `top_tags` VARCHAR(2000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type` INT(11) NOT NULL,
  `data` BLOB NOT NULL,
  `score` DECIMAL(28,14) NOT NULL,
  `parent` INT(11) NOT NULL,
  `niveau` INT(11) NOT NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `score` (`score` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 1281
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_exi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_exi` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_exi` (
  `exi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `uti_id` INT(11) NOT NULL,
  `nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `prenom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lft` INT(11) NOT NULL,
  `rgt` INT(11) NOT NULL,
  `parent` INT(11) NOT NULL,
  `niveau` INT(11) NOT NULL,
  `maj` DATETIME NOT NULL,
  `poids` INT(11) NOT NULL,
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nait` DATE NOT NULL,
  `mort` DATE NOT NULL,
  `isni` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `flux_uti_uti_id` INT(11) NOT NULL,
  PRIMARY KEY (`exi_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_geos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_geos` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_geos` (
  `geo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_instant` INT(11) NOT NULL,
  `lat` DECIMAL(12,8) NOT NULL,
  `lng` DECIMAL(12,8) NOT NULL,
  `alt` DECIMAL(20,10) NOT NULL COMMENT 'en mètre',
  `geo` GEOMETRY NOT NULL,
  `zoom_min` INT(11) NOT NULL,
  `zoom_max` INT(11) NOT NULL,
  `adresse` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `codepostal` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ville` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `pays` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `kml` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type_carte` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `maj` DATETIME NOT NULL,
  PRIMARY KEY (`geo_id`),
  INDEX `id_instant` (`id_instant` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_monade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_monade` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_monade` (
  `monade_id` INT(11) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `maj` DATETIME NOT NULL,
  PRIMARY KEY (`monade_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_rapport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_rapport` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_rapport` (
  `rapport_id` INT(11) NOT NULL AUTO_INCREMENT,
  `monade_id` INT(11) NOT NULL,
  `src_id` INT(11) NOT NULL,
  `src_obj` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `dst_id` INT(11) NOT NULL,
  `dst_obj` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `pre_id` INT(11) NOT NULL COMMENT 'id prédicat',
  `pre_obj` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'obj prédicat',
  `geo_id` INT(11) NOT NULL,
  `maj` DATETIME NOT NULL,
  `niveau` INT(11) NOT NULL,
  `valeur` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `flux_doc_doc_id` INT(11) NOT NULL,
  `flux_exi_exi_id` INT(11) NOT NULL,
  `flux_geos_geo_id` INT(11) NOT NULL,
  `flux_tag_tag_id` INT(11) NOT NULL,
  `flux_acti_acti_id` INT(11) NOT NULL,
  `flux_monade_monade_id` INT(11) NOT NULL,
  `flux_uti_uti_id` INT(11) NOT NULL,
  PRIMARY KEY (`rapport_id`),
  INDEX `idxMonade` (`monade_id` ASC) VISIBLE,
  INDEX `idxSrc` (`src_obj` ASC) VISIBLE,
  INDEX `idxDst` (`dst_obj` ASC) VISIBLE,
  INDEX `idxPre` (`pre_obj` ASC) VISIBLE,
  INDEX `idxSrcId` (`src_id` ASC) VISIBLE,
  INDEX `idxDstId` (`dst_id` ASC) VISIBLE,
  INDEX `idxPreId` (`pre_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 19939
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_tag` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_tag` (
  `tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(225) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `desc` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ns` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `niveau` INT(11) NOT NULL,
  `parent` INT(11) NOT NULL,
  `lft` INT(11) NOT NULL,
  `rgt` INT(11) NOT NULL,
  `uri` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`tag_id`),
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `lft_rgt` (`lft` ASC, `rgt` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 16809
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`flux_uti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`flux_uti` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`flux_uti` (
  `uti_id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(2000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `maj` VARCHAR(225) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `flux` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `mdp` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `role` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `mdp_sel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ip_inscription` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `date_inscription` DATETIME NOT NULL,
  PRIMARY KEY (`uti_id`),
  INDEX `login` (`login`(333) ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`geo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`geo` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`geo` (
  `id_geo` INT NOT NULL AUTO_INCREMENT,
  `lat` DECIMAL(10,7) NULL,
  `lng` DECIMAL(10,7) NULL,
  `alt` INT NULL COMMENT 'mètre',
  `geo` MEDIUMTEXT NULL,
  `ruche_id_ruche` INT NOT NULL,
  PRIMARY KEY (`id_geo`, `ruche_id_ruche`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flux_ontostats`.`ruche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flux_ontostats`.`ruche` ;

CREATE TABLE IF NOT EXISTS `flux_ontostats`.`ruche` (
  `id_ruche` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ruche`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
